
[build]
	publish = "_site"
	command = "npx @11ty/eleventy"

[[plugins]]

# caching plugin so I don't rebuild all the images on each load

package = "netlify-plugin-cache"
  [plugins.inputs]
  # Optional (but highly recommended). Defaults to [".cache"].
  paths = [
	"_site/img/", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
	]