[build]
	publish = "_site"
	command = "npm run build"

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 1.0
		accessibility = 0.95
		best-practices = 0.95
		seo = 1.0

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"

[[plugins]]

# cacheing plugin so I don't rebuild all the images on each load

package = "netlify-plugin-cache"
  [plugins.inputs]
  # Optional (but highly recommended). Defaults to [".cache"].
  paths = ["img"]